# Generated by Django 4.1.7 on 2023-04-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=264)),
                ('startingBid', models.IntegerField()),
                ('currentBid', models.IntegerField()),
                ('newBid', models.IntegerField()),
            ],
        ),
    ]
