# Generated by Django 4.1.7 on 2023-04-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='currentBid',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='newBid',
        ),
    ]
