# Generated by Django 4.1.7 on 2023-05-01 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listings_currentbid_remove_listings_newbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlistItem', to=settings.AUTH_USER_MODEL),
        ),
    ]
