# Generated by Django 4.1.7 on 2023-05-06 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_creater_alter_bids_id_alter_comments_id_and_more'),
    ]

    