# Generated by Django 4.1.7 on 2023-05-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_creater'),
    ]

    
