# Generated by Django 4.1.7 on 2023-05-09 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bids_comments'),
    ]

    
