# Generated by Django 4.1.7 on 2023-05-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listings_creater'),
    ]

    