# Generated by Django 4.1.7 on 2023-05-09 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_listings_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='creater',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='UserID', to=settings.AUTH_USER_MODEL),
        ),
    ]
