# Generated by Django 4.1.7 on 2023-05-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_bids_title_remove_comments_username_bids_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='allComments', to='auctions.listings'),
        ),
    ]
