# Generated by Django 4.1.7 on 2023-05-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_listings_comment_comments_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='allComments',
        ),
    ]
